### ISSUE TITLE
Baseline ProfileのファイルをCIで作成してPR作成させる

### ISSUE THREAD

**Issue by ShinichiroFunatsu** [ShinichiroFunatsu/BaselineProfile#4]
## baseline-profile.txtの作成
gradle タスクの実行
```bash
#!/usr/bin/env bash
set -ex
./gradlew :benchmark:cleanManagedDevices --unused-only
./gradlew :benchmark:pixel6ProApi31DevelopBenchmarkAndroidTest -P android.testoptions.manageddevices.emulator.gpu="swiftshader_indirect" -P android.testInstrumentationRunnerArguments.androidx.benchmark.enabledRules=BaselineProfile
mv "benchmark/build/outputs/managed_device_android_test_additional_output/flavors/develop/pixel6ProApi31/BaselineProfileGenerator_generate-baseline-prof.txt" "app/src/main/baseline-profile.txt"
```

 ## GitHubへプルリクエスト作成
- git pushを成功させるために、ssk-keyの書き込み権限が必要
- `POST https://api.github.com/repos/ShinichiroFunatsu/BaselineProfile/pulls`でプルリクエストを作成させるために、GitHubでトークンを作成しCI側に設定する必要あり。

```bash
#!/usr/bin/env bash
set -ex

git checkout -b baseline-profile
git add .
git commit -m "chore:update baseline-profile.txt"
git push origin baseline-profile

curl -L \
  -X POST \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer ${GITHUB_TOKEN}"\
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/ShinichiroFunatsu/BaselineProfile/pulls \
  -d '{"title":"Update baseline-profile.txt","body":"[skip ci]\nThis is an automated pull request","head":"baseline-profile","base":"main"}'
```

**Comment by ShinichiroFunatsu** [comment]
bitrise用ymlファイルの例
```yaml

  create-baseline-profile:
    description: |
      Runs generate Baseline Profile task.
    steps:
    - activate-ssh-key@4: {}
    - git-clone@8: {}
    - set-java-version@1:
        inputs:
        - set_java_version: '17'
    - restore-gradle-cache@1: {}
    - install-missing-android-tools@3:
        inputs:
        - gradlew_path: "$PROJECT_LOCATION/gradlew"
    - script@1:
        inputs:
        - content: |-
            #!/usr/bin/env bash
            set -ex
            ./gradlew :benchmark:cleanManagedDevices --unused-only
            ./gradlew :benchmark:pixel6ProApi31DevelopBenchmarkAndroidTest -P android.testoptions.manageddevices.emulator.gpu="swiftshader_indirect" -P android.testInstrumentationRunnerArguments.androidx.benchmark.enabledRules=BaselineProfile
            mv "benchmark/build/outputs/managed_device_android_test_additional_output/flavors/develop/pixel6ProApi31/BaselineProfileGenerator_generate-baseline-prof.txt" "app/src/main/baseline-profile.txt"
        title: Execute Generate Baseline Profile Task
    - script@1:
        title: Create Pull Request for Baseline Profile
        inputs:
        - content: |-
            #!/usr/bin/env bash
            set -ex

            git checkout -b baseline-profile
            git add .
            git commit -m "chore:update baseline-profile.txt"
            git push origin baseline-profile


            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${GITHUB_TOKEN}"\
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/ShinichiroFunatsu/BaselineProfile/pulls \
              -d '{"title":"Update baseline-profile.txt","body":"[skip ci]\nThis is an automated pull request","head":"baseline-profile","base":"main"}'
    - save-gradle-cache@1: {} // 必要?
    - deploy-to-bitrise-io@2: {} // 必要?
```
